/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BucketList: typeof import('./src/components/bucket/bucket-list.vue')['default']
    BucketListItem: typeof import('./src/components/bucket/bucket-list-item.vue')['default']
    Countdown: typeof import('./src/components/countdown.vue')['default']
    Navbar: typeof import('./src/components/layout/navbar.vue')['default']
    QueMultipleCard: typeof import('./src/components/question/que-multiple-card.vue')['default']
    QueSingleCard: typeof import('./src/components/question/que-single-card.vue')['default']
    Question: typeof import('./src/components/question/question.vue')['default']
    QuestionMap: typeof import('./src/components/question/question-map.vue')['default']
    QuestionWrap: typeof import('./src/components/question/question-wrap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
