/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth': RouteRecordInfo<
      '/auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | '/auth/signin'
      | '/auth/signup'
    >,
    '/auth/signin': RouteRecordInfo<
      '/auth/signin',
      '/auth/signin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/signup': RouteRecordInfo<
      '/auth/signup',
      '/auth/signup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home': RouteRecordInfo<
      '/home',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | '/home/bucket/'
      | '/home/bucket/[id]'
      | '/home/record/'
    >,
    '/home/bucket/': RouteRecordInfo<
      '/home/bucket/',
      '/home/bucket',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/bucket/[id]': RouteRecordInfo<
      '/home/bucket/[id]',
      '/home/bucket/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/home/record/': RouteRecordInfo<
      '/home/record/',
      '/home/record',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/auth.vue': {
      routes:
        | '/auth'
        | '/auth/signin'
        | '/auth/signup'
      views:
        | 'default'
    }
    'src/pages/auth/signin.vue': {
      routes:
        | '/auth/signin'
      views:
        | never
    }
    'src/pages/auth/signup.vue': {
      routes:
        | '/auth/signup'
      views:
        | never
    }
    'src/pages/home.vue': {
      routes:
        | '/home'
        | '/home/bucket/'
        | '/home/bucket/[id]'
        | '/home/record/'
      views:
        | 'default'
    }
    'src/pages/home/bucket/index.vue': {
      routes:
        | '/home/bucket/'
      views:
        | never
    }
    'src/pages/home/bucket/[id].vue': {
      routes:
        | '/home/bucket/[id]'
      views:
        | never
    }
    'src/pages/home/record/index.vue': {
      routes:
        | '/home/record/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
